baseURL = 'https://darianliang.github.io/'
languageCode = 'en-us'
title = 'Darian Liang'
theme = 'PaperMod'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[menu]
  [[menu.main]]
    name = "Experience"
    url  = "#experience"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url  = "#projects"
    weight = 2
  [[menu.main]]
    name = "Skills"
    url  = "#skills"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url  = "#contact"
    weight = 4
[params]
  homeInfoParams = false
  defaultTheme = "auto"