baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[menu]
  [[menu.main]]
    name = "Experience"
    url  = "#experience"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url  = "#projects"
    weight = 2
  [[menu.main]]
    name = "Skills"
    url  = "#skills"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url  = "#contact"
    weight = 4
